### ISSUE TITLE
Can I have few .hedra directly?

### ISSUE THREAD

**Issue by MarsVegetables** [mlivesu/LoopyCuts#4]
Hi,
Can I directly have some .hedra file, since I am not able to compile LoopyCuts. [Issue at Coinlib](https://github.com/mlivesu/cinolib/issues/151#issuecomment-1230428463).
Thank you for your good work.

**Comment by mlivesu** [comment]
hi, sorry for the delay, I just noticed this issue. 
I pushed in the repo a zip file with the original output meshes shown in the paper. 
There are both full hexahedral meshes (MESH format) and hybrid meshes (cinolib's HYBRID format)
